# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{has_token}
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["laserlemon"]
  s.date = %q{2009-10-07}
  s.description = %q{Generate unique tokens on your ActiveRecord models}
  s.email = %q{steve@laserlemon.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/has_token_migration/has_token_migration_generator.rb",
     "generators/has_token_migration/templates/migration.rb",
     "has_token.gemspec",
     "init.rb",
     "lib/has_token.rb",
     "lib/token.rb",
     "test/has_token_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/laserlemon/has_token}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{laser-lemon}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Generate unique tokens on your ActiveRecord models}
  s.test_files = [
    "test/has_token_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
